spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://14.32.74.89:3306/portfolio?serverTimezone=Asia/Seoul
    username: coffee_writer
    password: coffee
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none